
#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/tcl/U3A_7_3G

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := generic

# APEX
OVERRIDE_TARGET_FLATTEN_APEX := true

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := u3a3gvf
TARGET_NO_BOOTLOADER := true

TW_MAX_BRIGHTNESS := 400
TW_DEFAULT_BRIGHTNESS := 200
TW_THEME := portrait_hdpi
TW_FRAMERATE := 60
TARGET_SCREEN_WIDTH := 600
TARGET_SCREEN_HEIGHT := 1024

# Kernel
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_CMDLINE := bootopt=64S3,32S1,32S1 buildvariant=eng
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_KERNEL_CONFIG := U3A_7_3G_defconfig
TARGET_KERNEL_SOURCE := kernel/tcl/U3A_7_3G

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
endif

# Partitions
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_BOOTIMAGE_PARTITION_SIZE := 6510592
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 9832448

# Platform
TARGET_BOARD_PLATFORM := mt6580

# Properties
#TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop
TW_NO_LEGACY_PROPS := true
#TW_INCLUDE_LIBRESETPROP := true

# Filesystems
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab
RECOVERY_SDCARD_ON_DATA := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_USES_MKE2FS := true
TW_INCLUDE_NTFS_3G := true
BOARD_HAS_LARGE_FILESYSTEM := true
TW_NO_BIND_SYSTEM := true

# Security patch level
VENDOR_SECURITY_PATCH := 2019-08-05

# Misc
TW_USE_TOOLBOX := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
TW_USE_LEGACY_BATTERY_SERVICES := true

# Making the recovery.img smaller
BOARD_HAS_NO_REAL_SDCARD := true

PRODUCT_FULL_TREBLE := false
PRODUCT_COMPATIBLE_PROPERTY_OVERRIDE := false
TARGET_USES_64_BIT_BINDER := false
MTK_BOOTIMAGE_OVERSIZE := true
BOARD_HAS_MTK_HARDWARE := true
KERNEL_COMPRESSION := gzip

# Version
TW_DEVICE_VERSION := SavedByLight
